sonar.projectKey=MiltonJ23_WouriFS
sonar.organization=miltonj23
sonar.projectName=WouriFS
sonar.projectVersion=3.0

sonar.sources=.
sonar.exclusions=api/gen/**/*,vendor/**,**/*_test.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
